# Auto-generated R wrappers via rextendr
#
# These wrappers provide idiomatic R interfaces to the Rust functions
# exported by the extendr module. The actual function implementations
# are generated by rextendr::document() which reads the #[extendr]
# attributes and generates corresponding R code.
#
# To regenerate:
#   rextendr::document()
#
# The Rust side defines:
#   - ferromode_r_version() -> character
#   - emd(signal, config) -> list
#   - eemd(signal, ensemble_config, emd_config) -> list
#   - ceemd(signal, ensemble_config, emd_config) -> list
#   - ceemdan(signal, ensemble_config, emd_config) -> list
#   - iceemdan(signal, ensemble_config, emd_config) -> list
#   - memd(signal, config) -> list
#   - namemd(signal, config) -> list
#   - vmd(signal, config) -> list
#   - reconstruct(result) -> numeric
