[package]
name = "ferromode-r"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "R bindings for Ferromode via extendr"

[lib]
name = "ferromodeR"
crate-type = ["staticlib"]

[dependencies]
ferromode = { path = "../ferromode" }
extendr-api = "0.9"

[lints]
workspace = true
