[package]
name = "ferromode-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "WASM bindings for Ferromode via wasm-bindgen"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ferromode = { path = "../ferromode" }
wasm-bindgen = "0.2"

[lints]
workspace = true
