"""Type stubs for ferromode Python bindings.

Autogenerated from PyO3 definitions for IDE autocompletion.
"""

from __future__ import annotations

from typing import Optional
import numpy as np
from numpy import ndarray

class BoundaryCondition:
    def __init__(self, value: str) -> None: ...
    def __repr__(self) -> str: ...

class StoppingCriterion:
    def __init__(self, value: str) -> None: ...
    def __repr__(self) -> str: ...

class AlgorithmType:
    def __init__(self, value: str) -> None: ...
    def __repr__(self) -> str: ...

class EmdConfig:
    def __init__(
        self,
        max_imfs: Optional[int] = None,
        boundary_condition: Optional[BoundaryCondition] = None,
        reconstruction_tolerance: Optional[float] = None,
        validate_reconstruction: Optional[bool] = None,
        sd_threshold: Optional[float] = None,
        s_number: Optional[int] = None,
        max_sifting_iterations: Optional[int] = None,
        energy_threshold: Optional[float] = None,
    ) -> None: ...

class EnsembleConfig:
    def __init__(
        self,
        num_ensembles: Optional[int] = None,
        noise_std: Optional[float] = None,
        seed: Optional[int] = None,
    ) -> None: ...

class MemdConfig:
    def __init__(
        self,
        max_imfs: Optional[int] = None,
        num_directions: Optional[int] = None,
        sd_threshold: Optional[float] = None,
        s_number: Optional[int] = None,
        max_sifting_iterations: Optional[int] = None,
    ) -> None: ...

class NaMemdConfig:
    def __init__(
        self,
        n_noise_channels: Optional[int] = None,
        noise_std: Optional[float] = None,
        seed: Optional[int] = None,
        max_imfs: Optional[int] = None,
        num_directions: Optional[int] = None,
    ) -> None: ...

class VmdConfig:
    def __init__(
        self,
        n_modes: Optional[int] = None,
        alpha: Optional[float] = None,
        tau: Optional[float] = None,
        tol: Optional[float] = None,
        max_iterations: Optional[int] = None,
    ) -> None: ...

class ImfCollectionPy:
    def imfs(self) -> ndarray: ...
    def residue(self) -> ndarray: ...
    def reconstruct(self) -> ndarray: ...
    def n_imfs(self) -> int: ...
    def orthogonality_index(self) -> float: ...

class HilbertResultPy:
    def instantaneous_amplitude(self) -> ndarray: ...
    def instantaneous_frequency(self) -> ndarray: ...
    def marginal_spectrum(self) -> ndarray: ...

class DecompositionResultPy:
    def algorithm(self) -> AlgorithmType: ...
    def elapsed_ms(self) -> float: ...
    def n_siftings(self) -> int: ...
    def config_snapshot(self) -> str: ...
    def imfs(self) -> ImfCollectionPy: ...
    def reconstruct(self) -> ndarray: ...
    def hilbert(self, sample_rate: float) -> HilbertResultPy: ...

def emd(
    signal: ndarray,
    config: Optional[EmdConfig] = None,
) -> DecompositionResultPy: ...
def eemd(
    signal: ndarray,
    ensemble_config: Optional[EnsembleConfig] = None,
    emd_config: Optional[EmdConfig] = None,
) -> DecompositionResultPy: ...
def ceemd(
    signal: ndarray,
    ensemble_config: Optional[EnsembleConfig] = None,
    emd_config: Optional[EmdConfig] = None,
) -> DecompositionResultPy: ...
def ceemdan(
    signal: ndarray,
    ensemble_config: Optional[EnsembleConfig] = None,
    emd_config: Optional[EmdConfig] = None,
) -> DecompositionResultPy: ...
def iceemdan(
    signal: ndarray,
    ensemble_config: Optional[EnsembleConfig] = None,
    emd_config: Optional[EmdConfig] = None,
) -> DecompositionResultPy: ...
def memd(
    signal: ndarray,
    config: Optional[MemdConfig] = None,
) -> DecompositionResultPy: ...
def namemd(
    signal: ndarray,
    config: Optional[NaMemdConfig] = None,
) -> DecompositionResultPy: ...
def vmd(
    signal: ndarray,
    config: Optional[VmdConfig] = None,
) -> DecompositionResultPy: ...
