#!/usr/bin/env python3
"""
Create a stub ONNX model for LSTM boundary prediction.

This script creates a minimal ONNX model that can be embedded in the Rust crate
for compilation. The actual trained model will replace this stub.

Usage:
    python create_stub_onnx_model.py --output crates/ferromode/models/lstm_predictor.onnx
"""

import argparse
import numpy as np
import struct
from pathlib import Path

# Minimal ONNX model bytes for a simple LSTM
# This is a stub that allows compilation; will be replaced with trained model


def create_minimal_onnx_lstm():
    """
    Create a minimal LSTM ONNX model.

    Returns a stub model (not trainable, for compilation only).
    The real model will be generated by train_lstm_predictor.py
    """
    # For now, create a very simple model that just repeats last value
    # This is sufficient for compilation and will be replaced during training

    # ONNX magic number and version
    onnx_bytes = bytearray()

    # Create minimal protobuf-encoded ONNX model
    # Format: ModelProto with GraphProto containing a simple constant node

    # This is a placeholder - actual ONNX generation requires onnx package
    # For compilation purposes, we'll create a minimal binary file

    # Create a minimal valid ONNX file by embedding a simple protobuf
    # Real implementation uses: onnx.helper.make_graph, onnx.helper.make_model

    return onnx_bytes or b"\x08\x00"  # Minimal placeholder


def create_stub_model_pytorch():
    """
    Create a stub using PyTorch (recommended approach).

    Requires: torch, torch.onnx
    """
    try:
        import torch
        import torch.nn as nn

        # Define minimal LSTM model
        class StubLSTM(nn.Module):
            def __init__(self):
                super().__init__()
                self.lstm1 = nn.LSTMCell(1, 128)
                self.lstm2 = nn.LSTMCell(128, 128)
                self.fc = nn.Linear(128, 10)

            def forward(self, x):
                # x shape: [batch_size, seq_len, 1]
                batch_size, seq_len = x.shape[:2]

                h1, c1 = torch.zeros(batch_size, 128), torch.zeros(batch_size, 128)
                h2, c2 = torch.zeros(batch_size, 128), torch.zeros(batch_size, 128)

                for t in range(seq_len):
                    x_t = x[:, t, :]  # [batch_size, 1]
                    h1, c1 = self.lstm1(x_t, (h1, c1))
                    h2, c2 = self.lstm2(h1, (h2, c2))

                output = self.fc(h2)  # [batch_size, 10]
                return output

        model = StubLSTM()
        model.eval()

        # Create dummy input: [batch_size=1, seq_len=20, features=1]
        dummy_input = torch.randn(1, 20, 1)

        return model, dummy_input

    except ImportError:
        print("PyTorch not available. Install with: pip install torch")
        return None, None


def main():
    parser = argparse.ArgumentParser(
        description="Create stub ONNX model for LSTM boundary prediction"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="crates/ferromode/models/lstm_predictor.onnx",
        help="Output path for ONNX model file",
    )
    parser.add_argument(
        "--method",
        choices=["pytorch", "minimal"],
        default="pytorch",
        help="Method to create stub model",
    )

    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if args.method == "pytorch":
        print("[1/3] Creating PyTorch LSTM model...")
        model, dummy_input = create_stub_model_pytorch()

        if model is None or dummy_input is None:
            print("ERROR: PyTorch not available")
            return 1

        try:
            import torch

            print("[2/3] Exporting to ONNX format...")
            torch.onnx.export(
                model,
                dummy_input,
                str(output_path),
                input_names=["input"],
                output_names=["output"],
                opset_version=14,
                do_constant_folding=True,
                verbose=False,
            )
        except Exception as e:
            print(f"ERROR exporting to ONNX: {e}")
            return 1
    else:
        print("[1/2] Creating minimal ONNX model...")
        onnx_bytes = create_minimal_onnx_lstm()
        with open(output_path, "wb") as f:
            f.write(onnx_bytes)

    print(f"[3/3] Model saved to: {output_path}")
    print(f"     Size: {output_path.stat().st_size} bytes")
    print()
    print("✓ Stub model created. This is suitable for compilation.")
    print("  Replace with trained model: python tools/train_lstm_predictor.py")

    return 0


if __name__ == "__main__":
    exit(main())
